import assert from 'node:assert/strict';
import { castBazi, ENGINE_VERSION, EPHEMERIS_MODEL } from '../src/index.js';
const chart = castBazi({year:2005,month:7,day:13,hour:8,minute:58,longitude:118.18});
assert.equal(chart.pillars.year, '乙酉');
assert.equal(chart.input.year, 2005);
assert.equal(chart.manifest.engineVersion, ENGINE_VERSION);
assert.equal(chart.manifest.ephemerisModel, EPHEMERIS_MODEL);
assert.equal(chart.manifest.ruleSet, 'bazi-core-0.1.0');
assert.match(chart.manifest.ruleSetHash, /^[0-9a-f]{16}$/);
console.log('chart smoke passed', chart.pillars, chart.manifest.ruleSetHash);
